"""Measure the shipped corpus against a deliberately broken copy of itself.

`torchlingo.preprocessing.alignment` provides two cheap checks for whether a
parallel corpus is actually parallel. This script runs them on
`data/example.tsv` twice: once as shipped, and once with the target side
rotated by a row so that no pair is a translation of itself.

The comparison is the point. A single score means nothing without knowing what
a broken corpus scores, and the second column supplies that from the same data,
so a reader can see the checks discriminate rather than take it on faith.

The scrambled column is a *conservative* stand-in for the real failure. The
corpus originally shipped as two independent documents zipped together, which
scored 0.001 correlation and 1.4% agreement. Rotating by one row is gentler:
neighbouring rows come from the same talk and are of similar length, so it
scores higher while still being unambiguously broken. If the checks separate
this, they separate anything worse.

Run:
    python scripts/diagnose_corpus.py

Writes `docs/docs/_generated/alignment_diagnosis.json` (the single source of
truth) and `docs/docs/_generated/alignment_diagnosis.md` (a table generated
from it, included into the data pipeline page). Nothing is hand-typed into
the docs.
"""

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

from torchlingo.preprocessing.alignment import (
    diagnose_alignment,
    shuffle_target_side,
)

DEFAULT_OUT = Path("docs/docs/_generated")
DEFAULT_CORPUS = Path("data/example.tsv")


def is_available(path: Path) -> bool:
    """Report whether a file holds real content rather than a Git LFS pointer.

    Args:
        path (Path): File to test.

    Returns:
        bool: True if the file exists and its content has been fetched.
    """
    if not path.exists():
        return False
    with path.open("rb") as handle:
        return not handle.read(23).startswith(b"version https://git-lfs")


def render_markdown(results: dict) -> str:
    """Generate the docs table from the measurements.

    Args:
        results (dict): Output of :func:`measure`.

    Returns:
        str: Markdown for inclusion into the data pipeline page.
    """
    shipped, scrambled = results["as_shipped"], results["scrambled"]
    return f"""<!-- Generated by scripts/diagnose_corpus.py. Do not edit by hand. -->

| Check | As shipped | Target side scrambled |
|---|---|---|
| Sentence length correlation | **{shipped["length_correlation"]}** | {scrambled["length_correlation"]} |
| Name and number agreement | **{shipped["anchor_agreement"]:.1%}** | {scrambled["anchor_agreement"]:.1%} |

Measured on all {results["rows"]:,} rows of `data/example.tsv`, with agreement
scored on the {shipped["scorable_rows"]:,} rows carrying a checkable name or
number. Reproduce with `python scripts/diagnose_corpus.py`.

The right-hand column is the same file with the target side rotated by one row,
so no pair is a translation of itself. Every structural property is unchanged:
same row count, same columns, no empty cells, real sentences on both sides.
Only these two checks notice.
"""


def measure(corpus: Path, sample: int) -> dict:
    """Diagnose the corpus as shipped and scrambled.

    Args:
        corpus (Path): TSV with `src` and `tgt` columns.
        sample (int): Maximum rows to score for anchor agreement.

    Returns:
        dict: Both reports plus the row count.
    """
    frame = pd.read_csv(corpus, sep="\t", dtype=str, keep_default_na=False)
    shipped = diagnose_alignment(frame, sample=sample)
    scrambled = diagnose_alignment(shuffle_target_side(frame), sample=sample)
    return {
        "corpus": str(corpus),
        "rows": len(frame),
        "as_shipped": vars(shipped),
        "scrambled": vars(scrambled),
    }


def main() -> int:
    """Diagnose the corpus and write the JSON and the generated table."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--corpus", type=Path, default=DEFAULT_CORPUS)
    parser.add_argument(
        "--sample",
        type=int,
        default=0,
        help="Rows to score for anchor agreement; 0 scores every row.",
    )
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    if not is_available(args.corpus):
        print(
            f"{args.corpus} is absent or an unfetched Git LFS pointer; skipping. "
            "Run `git lfs pull` to fetch it.",
            file=sys.stderr,
        )
        return 0

    frame_rows = sum(1 for _ in args.corpus.open(encoding="utf-8"))
    results = measure(args.corpus, args.sample or frame_rows)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / "alignment_diagnosis.json").write_text(
        json.dumps(results, indent=2) + "\n"
    )
    (args.out_dir / "alignment_diagnosis.md").write_text(render_markdown(results))

    for label in ("as_shipped", "scrambled"):
        row = results[label]
        print(
            f"{label:<12s} correlation={row['length_correlation']:<8} "
            f"agreement={row['anchor_agreement']:<8} "
            f"scorable={row['scorable_rows']:,}"
        )
    print(f"\nwrote {args.out_dir}/alignment_diagnosis.json and .md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
