"""Generate the reports in ``notes/reports/`` from their JSON sources.

``notes/reports/data/*.json`` holds measured numbers; the Markdown beside it is a build
artifact. This script is the only thing that should write that Markdown.

Run it two ways:

    python scripts/render_report.py            rewrite the Markdown
    python scripts/render_report.py --check    exit 1 if it is out of date

``--check`` is the point. Without it "generated" is an honour system: someone
hand-corrects one number in the Markdown, the JSON keeps the old value, and the two
disagree from then on with nothing to notice. This repository has already published a
chrF of 100.00 that should have been 78.40 and a decode length that held two different
values in two places -- both single numbers that nothing checked. See Task #81.

Every derived quantity -- ratios, exponents, percentage changes -- is computed here
rather than typed into the JSON, so that a rerun of the experiment cannot leave a stale
ratio behind next to a fresh measurement.
"""

from __future__ import annotations

import argparse
import itertools
import json
import math
import sys
from pathlib import Path

REPORTS = Path("notes/reports")
DATA = REPORTS / "data"

GENERATED_WARNING = (
    "<!-- GENERATED by scripts/render_report.py from "
    "notes/reports/data/length-ladder.json. Do not edit: run the script. -->"
)


def scaling_exponent(low: dict, high: dict) -> float | None:
    """Return the exponent *k* where memory scales as ``length ** k`` between two rungs.

    Solves ``high/low = (len_high/len_low) ** k`` for ``k``. Reported rather than
    asserted, because the ladder's own finding is that no single exponent fits the whole
    range: the linear embedding and feed-forward activations dominate at short lengths
    and attention only overtakes them further out.

    Args:
        low (dict): The shorter rung.
        high (dict): The longer rung.

    Returns:
        float | None: The exponent, or None when it cannot be computed.
    """
    lo_len, hi_len = low["effective_cap"], high["effective_cap"]
    lo_mem, hi_mem = low["device_held_gb"], high["device_held_gb"]
    if not all((lo_len, hi_len, lo_mem, hi_mem)) or lo_len >= hi_len or lo_mem <= 0:
        return None
    return math.log(hi_mem / lo_mem) / math.log(hi_len / lo_len)


def render_length_ladder(doc: dict) -> str:
    """Build the length-ladder report.

    Args:
        doc (dict): Parsed ``length-ladder.json``.

    Returns:
        str: The complete Markdown document.
    """
    cfg, rungs = doc["config"], doc["rungs"]
    quotable = [r for r in rungs if not r.get("do_not_quote")]
    first, last = quotable[0], quotable[-1]

    mem_span = last["device_held_gb"] / first["device_held_gb"]
    time_span = last["seconds_per_epoch"] / first["seconds_per_epoch"]

    out: list[str] = [
        GENERATED_WARNING,
        "",
        f"# {doc['title']}",
        "",
        doc["summary"].strip(),
        "",
        "## How it was measured",
        "",
        f"- **Corpus** — {cfg['corpus']}",
        (
            f"- **Model** — batch {cfg['batch_size']}, `d_model` {cfg['d_model']}, "
            f"{cfg['layers']} layers, {cfg['heads']} heads"
        ),
        (
            f"- **Runtime** — {cfg['device']}, {cfg['machine_ram_gb']} GiB machine, "
            f"bucketing {'on' if cfg['bucketing'] else 'off'}, AMP "
            f"{'on' if cfg['amp'] else 'off'}"
        ),
        f"- **Each rung** — {cfg['epochs']} epochs, seed {cfg['seed']}, its own process",
        "",
        (
            "`device held` is what the allocator holds, not what the model needs: on "
            "Metal that reserve is taken from the machine's own RAM, so it is the figure "
            "that decides whether anything else can run. `reclaimed` is what "
            "`empty_cache()` returns."
        ),
        "",
        "## The ladder",
        "",
        "| cap | device held | reclaimed | peak RSS | s/epoch | batches | pairs truncated |",
        "|---|---|---|---|---|---|---|",
    ]

    for r in rungs:
        cap = "none" if r["cap"] is None else str(r["cap"])
        trunc = (
            "—"
            if r.get("truncated_fraction") is None
            else f"{r['truncated_fraction'] * 100:.2f}%"
        )
        note = " ¹" if r.get("do_not_quote") else ""
        out.append(
            f"| {cap}{note} | {r['device_held_gb']:.2f} GiB | "
            f"{r['device_reclaimed_gb']:.2f} | {r['peak_resident_gb']:.2f} | "
            f"{r['seconds_per_epoch']:.1f} | {r['batches_per_epoch']:,} | {trunc} |"
        )

    out += [
        "",
        "¹ Not quotable as evidence about scaling: see the caveat below.",
    ]

    agreed = next((r for r in rungs if r["cap"] == cfg.get("agreed_cap")), None)
    uncapped = next((r for r in rungs if r["cap"] is None), None)
    if agreed and uncapped:
        saved = 1 - agreed["device_held_gb"] / uncapped["device_held_gb"]
        same_time = (
            abs(agreed["seconds_per_epoch"] - uncapped["seconds_per_epoch"]) < 0.5
        )
        out += [
            "",
            f"## What the cap at {agreed['cap']} actually buys",
            "",
            (
                "This is the result the ladder was built to get, and it is a better "
                "bargain than it looks."
            ),
            "",
            f"| | cap {agreed['cap']} | no cap |",
            "|---|---|---|",
            (
                f"| device held | **{agreed['device_held_gb']:.2f} GiB** | "
                f"{uncapped['device_held_gb']:.2f} GiB |"
            ),
            (
                f"| seconds/epoch | {agreed['seconds_per_epoch']:.1f} | "
                f"{uncapped['seconds_per_epoch']:.1f} |"
            ),
            f"| pairs truncated | {agreed['truncated_fraction'] * 100:.2f}% | 0% |",
            "",
            (
                f"**{saved * 100:.0f}% of the memory cost removed for "
                f"{agreed['truncated_fraction'] * 100:.2f}% of the data**, at "
                f"{'identical' if same_time else 'almost identical'} wall clock."
            ),
            "",
            (
                "The reason is that peak memory is set by the *longest* batch, not the "
                f"median one. Pairs above {agreed['cap']} subwords are a "
                f"{agreed['truncated_fraction'] * 100:.2f}% sliver of the corpus, but "
                "while they are present every epoch must allocate for them. Clipping the "
                "tail is therefore cheap in data and large in memory, which is precisely "
                "the trade a length cap exists to make."
            ),
            "",
            (
                "It also explains why wall clock does not move: the same number of "
                "batches still runs, and only the few longest ones get shorter."
            ),
        ]

    out += [
        "",
        "## Two levers, different shapes",
        "",
        (
            f"Across the quotable range — cap {first['cap']} to no cap "
            f"(effective {last['effective_cap']} subwords) — **memory moves "
            f"{mem_span:.0f}x while time moves {time_span:.2f}x.**"
        ),
        "",
        "So they are separate levers, and the one sentence worth giving a student is:",
        "",
        (
            "> **Batch count sets how long an epoch takes. The length cap sets whether "
            "it fits at all.**"
        ),
        "",
        (
            "If a session dies, the first thing to look at is the length cap, not the "
            "epoch count and not the batch size."
        ),
        "",
        "## Growth is not quadratic in the cap",
        "",
        (
            "Attention is quadratic in sequence length, so the cap was expected to be "
            "too. It is not, because attention is only part of the footprint: embedding "
            "and feed-forward activations are *linear* in length and dominate until "
            "sequences grow long enough for the quadratic term to overtake them."
        ),
        "",
        "| interval | length factor | memory factor | implied exponent |",
        "|---|---|---|---|",
    ]

    for low, high in itertools.pairwise(quotable):
        k = scaling_exponent(low, high)
        lo_cap = "none" if low["cap"] is None else low["cap"]
        hi_cap = "none" if high["cap"] is None else high["cap"]
        out.append(
            f"| {lo_cap} → {hi_cap} | "
            f"{high['effective_cap'] / low['effective_cap']:.2f}x | "
            f"{high['device_held_gb'] / low['device_held_gb']:.2f}x | "
            f"{'—' if k is None else f'{k:.2f}'} |"
        )

    out += [
        "",
        "## Caveats, which are the most reusable part of this",
        "",
    ]
    for caveat in doc["caveats"]:
        out.append(f"- {caveat.strip()}")

    out += ["", "## Corrections", ""]
    for correction in doc["corrections"]:
        out.append(f"- {correction.strip()}")

    out += [
        "",
        "## Open question this does not answer",
        "",
        doc["open_question"].strip(),
        "",
    ]
    return "\n".join(out)


RENDERERS = {"length-ladder": render_length_ladder}


def main() -> int:
    """Render every report, or check that the rendered copies are current."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if any report differs from its JSON",
    )
    args = parser.parse_args()

    stale: list[str] = []
    for name, renderer in RENDERERS.items():
        source = DATA / f"{name}.json"
        if not source.exists():
            print(f"missing {source}", file=sys.stderr)
            return 2
        expected = renderer(json.loads(source.read_text(encoding="utf-8")))
        target = REPORTS / f"{name}.md"
        current = target.read_text(encoding="utf-8") if target.exists() else None

        if args.check:
            if current != expected:
                stale.append(str(target))
            continue

        if current == expected:
            print(f"  unchanged  {target}")
        else:
            target.write_text(expected, encoding="utf-8")
            print(f"  written    {target}")

    if stale:
        print(
            "These reports are out of date with their JSON:\n"
            + "\n".join(f"  {s}" for s in stale)
            + "\n\nRun: python scripts/render_report.py",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print("  all reports current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
