"""Generate the reports in ``notes/reports/`` from their JSON sources.

``notes/reports/data/*.json`` holds measured numbers; the Markdown beside it is a build
artifact. This script is the only thing that should write that Markdown.

Run it two ways:

    python scripts/render_report.py            rewrite the Markdown
    python scripts/render_report.py --check    exit 1 if it is out of date

``--check`` is the point. Without it "generated" is an honour system: someone
hand-corrects one number in the Markdown, the JSON keeps the old value, and the two
disagree from then on with nothing to notice. This repository has already published a
chrF of 100.00 that should have been 78.40 and a decode length that held two different
values in two places -- both single numbers that nothing checked. See Task #81.

Every derived quantity -- ratios, exponents, percentage changes -- is computed here
rather than typed into the JSON, so that a rerun of the experiment cannot leave a stale
ratio behind next to a fresh measurement.
"""

from __future__ import annotations

import argparse
import itertools
import json
import math
import re
import sys
from pathlib import Path

REPORTS = Path("notes/reports")
DATA = REPORTS / "data"

GENERATED_WARNING = (
    "<!-- GENERATED by scripts/render_report.py from "
    "notes/reports/data/length-ladder.json. Do not edit: run the script. -->"
)


def scaling_exponent(low: dict, high: dict) -> float | None:
    """Return the exponent *k* where memory scales as ``length ** k`` between two rungs.

    Solves ``high/low = (len_high/len_low) ** k`` for ``k``. Reported rather than
    asserted, because the ladder's own finding is that no single exponent fits the whole
    range: the linear embedding and feed-forward activations dominate at short lengths
    and attention only overtakes them further out.

    Args:
        low (dict): The shorter rung.
        high (dict): The longer rung.

    Returns:
        float | None: The exponent, or None when it cannot be computed.
    """
    lo_len, hi_len = low["effective_cap"], high["effective_cap"]
    lo_mem, hi_mem = low["device_held_gb"], high["device_held_gb"]
    if not all((lo_len, hi_len, lo_mem, hi_mem)) or lo_len >= hi_len or lo_mem <= 0:
        return None
    return math.log(hi_mem / lo_mem) / math.log(hi_len / lo_len)


def render_length_ladder(doc: dict) -> str:
    """Build the length-ladder report.

    Args:
        doc (dict): Parsed ``length-ladder.json``.

    Returns:
        str: The complete Markdown document.
    """
    cfg, rungs = doc["config"], doc["rungs"]
    quotable = [r for r in rungs if not r.get("do_not_quote")]
    first, last = quotable[0], quotable[-1]

    mem_span = last["device_held_gb"] / first["device_held_gb"]
    time_span = last["seconds_per_epoch"] / first["seconds_per_epoch"]

    out: list[str] = [
        GENERATED_WARNING,
        "",
        f"# {doc['title']}",
        "",
        doc["summary"].strip(),
        "",
        "## How it was measured",
        "",
        f"- **Corpus** — {cfg['corpus']}",
        (
            f"- **Model** — batch {cfg['batch_size']}, `d_model` {cfg['d_model']}, "
            f"{cfg['layers']} layers, {cfg['heads']} heads"
        ),
        (
            f"- **Runtime** — {cfg['device']}, {cfg['machine_ram_gb']} GiB machine, "
            f"bucketing {'on' if cfg['bucketing'] else 'off'}, AMP "
            f"{'on' if cfg['amp'] else 'off'}"
        ),
        f"- **Each rung** — {cfg['epochs']} epochs, seed {cfg['seed']}, its own process",
        "",
        (
            "`device held` is what the allocator holds, not what the model needs: on "
            "Metal that reserve is taken from the machine's own RAM, so it is the figure "
            "that decides whether anything else can run. `reclaimed` is what "
            "`empty_cache()` returns."
        ),
        "",
        "## The ladder",
        "",
        "| cap | device held | reclaimed | peak RSS | s/epoch | batches | pairs truncated |",
        "|---|---|---|---|---|---|---|",
    ]

    for r in rungs:
        cap = "none" if r["cap"] is None else str(r["cap"])
        trunc = (
            "—"
            if r.get("truncated_fraction") is None
            else f"{r['truncated_fraction'] * 100:.2f}%"
        )
        note = " ¹" if r.get("do_not_quote") else ""
        out.append(
            f"| {cap}{note} | {r['device_held_gb']:.2f} GiB | "
            f"{r['device_reclaimed_gb']:.2f} | {r['peak_resident_gb']:.2f} | "
            f"{r['seconds_per_epoch']:.1f} | {r['batches_per_epoch']:,} | {trunc} |"
        )

    out += [
        "",
        "¹ Not quotable as evidence about scaling: see the caveat below.",
    ]

    agreed = next((r for r in rungs if r["cap"] == cfg.get("agreed_cap")), None)
    uncapped = next((r for r in rungs if r["cap"] is None), None)
    if agreed and uncapped:
        saved = 1 - agreed["device_held_gb"] / uncapped["device_held_gb"]
        same_time = (
            abs(agreed["seconds_per_epoch"] - uncapped["seconds_per_epoch"]) < 0.5
        )
        out += [
            "",
            f"## What the cap at {agreed['cap']} actually buys",
            "",
            (
                "This is the result the ladder was built to get, and it is a better "
                "bargain than it looks."
            ),
            "",
            f"| | cap {agreed['cap']} | no cap |",
            "|---|---|---|",
            (
                f"| device held | **{agreed['device_held_gb']:.2f} GiB** | "
                f"{uncapped['device_held_gb']:.2f} GiB |"
            ),
            (
                f"| seconds/epoch | {agreed['seconds_per_epoch']:.1f} | "
                f"{uncapped['seconds_per_epoch']:.1f} |"
            ),
            f"| pairs truncated | {agreed['truncated_fraction'] * 100:.2f}% | 0% |",
            "",
            (
                f"**{saved * 100:.0f}% of the memory cost removed for "
                f"{agreed['truncated_fraction'] * 100:.2f}% of the data**, at "
                f"{'identical' if same_time else 'almost identical'} wall clock."
            ),
            "",
            (
                "The reason is that peak memory is set by the *longest* batch, not the "
                f"median one. Pairs above {agreed['cap']} subwords are a "
                f"{agreed['truncated_fraction'] * 100:.2f}% sliver of the corpus, but "
                "while they are present every epoch must allocate for them. Clipping the "
                "tail is therefore cheap in data and large in memory, which is precisely "
                "the trade a length cap exists to make."
            ),
            "",
            (
                "It also explains why wall clock does not move: the same number of "
                "batches still runs, and only the few longest ones get shorter."
            ),
        ]

    out += [
        "",
        "## Two levers, different shapes",
        "",
        (
            f"Across the quotable range — cap {first['cap']} to no cap "
            f"(effective {last['effective_cap']} subwords) — **memory moves "
            f"{mem_span:.0f}x while time moves {time_span:.2f}x.**"
        ),
        "",
        "So they are separate levers, and the one sentence worth giving a student is:",
        "",
        (
            "> **Batch count sets how long an epoch takes. The length cap sets whether "
            "it fits at all.**"
        ),
        "",
        (
            "If a session dies, the first thing to look at is the length cap, not the "
            "epoch count and not the batch size."
        ),
        "",
        "## Growth is not quadratic in the cap",
        "",
        (
            "Attention is quadratic in sequence length, so the cap was expected to be "
            "too. It is not, because attention is only part of the footprint: embedding "
            "and feed-forward activations are *linear* in length and dominate until "
            "sequences grow long enough for the quadratic term to overtake them."
        ),
        "",
        "| interval | length factor | memory factor | implied exponent |",
        "|---|---|---|---|",
    ]

    for low, high in itertools.pairwise(quotable):
        k = scaling_exponent(low, high)
        lo_cap = "none" if low["cap"] is None else low["cap"]
        hi_cap = "none" if high["cap"] is None else high["cap"]
        out.append(
            f"| {lo_cap} → {hi_cap} | "
            f"{high['effective_cap'] / low['effective_cap']:.2f}x | "
            f"{high['device_held_gb'] / low['device_held_gb']:.2f}x | "
            f"{'—' if k is None else f'{k:.2f}'} |"
        )

    out += [
        "",
        "## Caveats, which are the most reusable part of this",
        "",
    ]
    for caveat in doc["caveats"]:
        out.append(f"- {caveat.strip()}")

    out += ["", "## Corrections", ""]
    for correction in doc["corrections"]:
        out.append(f"- {correction.strip()}")

    out += [
        "",
        "## Open question this does not answer",
        "",
        doc["open_question"].strip(),
        "",
    ]
    return "\n".join(out)


def render_a8_benchmark(doc: dict) -> str:
    """Build the Assignment 8 benchmark and learning-curve report.

    Two things this renderer refuses to do, because both would produce a plausible and wrong
    picture:

    It never puts runs from different split families on one line. The curve's splits are
    nested with a single shared tokenizer; the A8 baseline used its own split and fit its own
    tokenizer. Two 100K runs from the two families differ by both, so a difference between
    them cannot be attributed to anything in particular.

    And it always says whether a point converged or ran out of budget. A converged point
    reports the best that much data can do; a capped one reports what it got in the budget.
    Drawing one line through both understates wherever the caps fall.

    Args:
        doc (dict): Parsed ``a8-benchmark.json``.

    Returns:
        str: The complete Markdown document.
    """
    cfg, runs = doc["config"], doc["runs"]
    curve = [r for r in runs if r["split_family"] == "curve" and r["pairs"]]
    baseline = [r for r in runs if r["split_family"] == "a8-baseline"]
    scales = sorted({r["d_model"] for r in curve})

    out = [
        GENERATED_WARNING.replace("length-ladder.json", "a8-benchmark.json"),
        "",
        f"# {doc['title']}",
        "",
        doc["summary"].strip(),
        "",
        "## How to read this",
        "",
        "Every row says **why it stopped**, and that decides what its score means:",
        "",
        (
            "- **converged** — validation stopped improving. This is the best that much data can "
            "do at that model size."
        ),
        (
            "- **budget-capped** — it hit the optimizer-step budget while still improving. This is "
            "what it got in the budget, and it is a *floor* rather than a ceiling."
        ),
        "",
        (
            "Comparing the two kinds as if they were one measurement understates every capped "
            "point. They are kept labelled rather than averaged."
        ),
        "",
        (
            "**The two families are also not comparable with each other.** The A8 baseline used "
            "its own split and fit its own tokenizer, on Apple Metal; every curve row used the "
            "nested splits with one shared tokenizer, on an A100. A 100,000-pair row appears in "
            "both, and the two differ by split, tokenizer and device at once — so the gap "
            "between them is not attributable to any one of the three."
        ),
        "",
        "## Assignment 8's own configuration",
        "",
        f"The A8 baseline: {cfg['corpus']}, {cfg['model']}.",
        "",
        "| epochs | BLEU | chrF | wall clock | stopped because |",
        "|---|---|---|---|---|",
    ]
    for r in sorted(baseline, key=lambda r: r["epochs_run"]):
        out.append(
            f"| {r['epochs_run']} | **{r['bleu']:.2f}** | {r['chrf']:.2f} | "
            f"{r['train_minutes']:.1f} min | {r['regime']} |"
        )

    if len(baseline) >= 2:
        lo, hi = sorted(baseline, key=lambda r: r["epochs_run"])[:2]
        out += [
            "",
            (
                f"**{lo['epochs_run']} epochs is not enough.** Going to {hi['epochs_run']} buys "
                f"**{hi['bleu'] - lo['bleu']:+.2f} BLEU**, and only the longer run converged. The "
                "assignment's 30-to-36 recommendation stops while the model is still improving."
            ),
            "",
            (
                "**So the instruction should be a step budget rather than an epoch count**: train "
                "until validation stops improving, which is about 100,000 optimizer steps. That "
                "phrasing survives a student changing their corpus size, where a fixed epoch count "
                "does not."
            ),
        ]

    # Before the numbers, not after. The design is what makes the curve worth reading at all,
    # and the scripts that implement it are in the private repository -- so without this
    # section the report asks to be trusted on exactly the point that decides whether a gain
    # belongs to the data or to the compute that came with it.
    if doc.get("design"):
        out += ["", "## How the comparison is controlled", ""]
        for item in doc["design"]:
            out.append(f"- {item.strip()}")

    out += ["", "## The learning curve", ""]
    header = "| pairs | " + " | ".join(f"d_model {d}" for d in scales) + " |"
    out += [header, "|" + "---|" * (len(scales) + 1)]
    for pairs in sorted({r["pairs"] for r in curve}):
        cells = []
        for d in scales:
            hit = next(
                (r for r in curve if r["pairs"] == pairs and r["d_model"] == d), None
            )
            if hit is None:
                cells.append("—")
            else:
                mark = "" if hit["regime"] == "converged" else r"\*"
                cells.append(f"{hit['bleu']:.2f}{mark}")
        out.append(f"| {pairs:,} | " + " | ".join(cells) + " |")
    out += ["", "An asterisk marks a budget-capped point: a floor, not a ceiling.", ""]

    for d in scales:
        col = sorted((r for r in curve if r["d_model"] == d), key=lambda r: r["pairs"])
        if len(col) < 2:
            continue
        params = col[0]["parameters"]
        first, last = col[0], col[-1]
        factor = last["pairs"] / first["pairs"]
        out.append(
            f"- **d_model {d}** ({params:,} parameters): {factor:.0f}x the data, from "
            f"{first['pairs']:,} to {last['pairs']:,}, moves BLEU "
            f"{first['bleu']:.2f} to {last['bleu']:.2f} — **{last['bleu'] - first['bleu']:+.2f}**."
        )

    # What capacity is worth at each corpus size, computed rather than typed. The findings
    # below quote these numbers in prose, and prose is where a figure goes stale unnoticed --
    # one claim in this report already said "three of six steps are negative" when two were.
    # Putting the derived table next to the prose means a reader sees both, and a future
    # mismatch is visible instead of needing to be remembered.
    if len(scales) >= 2:
        # Compare the largest scale against the one Assignment 8 actually uses, not against
        # the smallest. The smallest exists to establish a capacity floor; nobody is choosing
        # between it and anything. The decision in front of a reader is whether A8's own
        # configuration is the right one, so that is the baseline the table has to use.
        baseline = next(
            (
                r["d_model"]
                for r in doc["runs"]
                if r["split_family"] == "a8-baseline" and r["d_model"] in scales
            ),
            scales[0],
        )
        small, large = baseline, scales[-1]
        if small == large:
            small = scales[0]
        pairs_both = sorted(
            {r["pairs"] for r in curve if r["d_model"] == small}
            & {r["pairs"] for r in curve if r["d_model"] == large}
        )
        if pairs_both:
            out += [
                "",
                f"### What capacity buys: d_model {large} minus d_model {small}",
                "",
                f"| pairs | d_model {small} | d_model {large} | difference |",
                "|---|---|---|---|",
            ]
            for pairs in pairs_both:
                lo = next(
                    r for r in curve if r["pairs"] == pairs and r["d_model"] == small
                )
                hi = next(
                    r for r in curve if r["pairs"] == pairs and r["d_model"] == large
                )
                out.append(
                    f"| {pairs:,} | {lo['bleu']:.2f} | {hi['bleu']:.2f} | "
                    f"**{hi['bleu'] - lo['bleu']:+.2f}** |"
                )

    out += ["", "## What it means", ""]
    for finding in doc["findings"]:
        out.append(f"- {finding.strip()}")

    out += ["", "## Caveats", ""]
    for caveat in doc["caveats"]:
        out.append(f"- {caveat.strip()}")

    # Corrections are part of the report, not a changelog kept elsewhere. A result that was
    # circulated and later turned out to be wrong has to be findable by whoever acted on it,
    # and the place they will look is the report -- not a commit message. Optional, because a
    # report with nothing to correct should not carry an empty heading.
    if doc.get("corrections"):
        out += ["", "## Corrections to earlier versions of this report", ""]
        for correction in doc["corrections"]:
            out.append(f"- {correction.strip()}")

    out.append("")
    return "\n".join(out)


_PROBE_HEADER = re.compile(
    r"^(?P<gpu>.+): (?P<total>[\d.]+) GiB, (?P<free>[\d.]+) free$"
)
_PROBE_ROW = re.compile(
    r"^(?P<model>\S+)\s+vocab\s+(?P<vocab>[\d,]+)\s+len\s+(?P<length>\d+)\s+"
    r"(?:peak\s+(?P<peak>[\d.]+) GiB, (?P<ms>\d+) ms/batch|OUT OF MEMORY)$"
)


def parse_probe_output(lines: list[str]) -> tuple[dict, list[dict]]:
    """Parse ``scripts/colab_memory_probe.py`` output, kept verbatim in the JSON.

    The raw lines are the source of truth rather than numbers retyped from them, so a
    transcription error cannot enter between the measurement and the report.

    Args:
        lines (list[str]): The probe's printed lines, header first.

    Returns:
        tuple: ``(header, rows)``. ``header`` has ``gpu``, ``total`` and ``free``; each row
            has ``model``, ``vocab``, ``length``, and ``peak`` and ``ms`` (None when the
            configuration ran out of memory).

    Raises:
        ValueError: If a line matches neither the header nor a row.
    """
    head = _PROBE_HEADER.match(lines[0].strip())
    if head is None:
        raise ValueError(f"unrecognised probe header: {lines[0]!r}")
    header = {
        "gpu": head["gpu"],
        "total": float(head["total"]),
        "free": float(head["free"]),
    }
    rows = []
    for line in lines[1:]:
        m = _PROBE_ROW.match(line.strip())
        if m is None:
            raise ValueError(f"unrecognised probe row: {line!r}")
        rows.append(
            {
                "model": m["model"],
                "vocab": int(m["vocab"].replace(",", "")),
                "length": int(m["length"]),
                "peak": float(m["peak"]) if m["peak"] else None,
                "ms": int(m["ms"]) if m["ms"] else None,
            }
        )
    return header, rows


def render_colab_memory(doc: dict) -> str:
    """Build the Colab GPU memory report for A8's two candidate models (Task #118).

    Peak memory is shown once, from the first session, only after checking every session
    agrees on it exactly; a disagreement is an error rather than an average, because the
    probe is deterministic and a difference would mean something changed. Times are shown
    per session, since they legitimately vary.

    Args:
        doc (dict): Parsed ``colab-memory.json``.

    Returns:
        str: The complete Markdown document.

    Raises:
        ValueError: If the sessions disagree on configuration or peak memory.
    """
    sessions = [
        (s["label"], *parse_probe_output(s["raw_output"])) for s in doc["sessions"]
    ]
    first_label, first_header, first_rows = sessions[0]
    for label, _, rows in sessions[1:]:
        for a, b in zip(first_rows, rows, strict=True):
            if (a["model"], a["vocab"], a["length"], a["peak"]) != (
                b["model"],
                b["vocab"],
                b["length"],
                b["peak"],
            ):
                raise ValueError(f"{label} disagrees with {first_label}: {a} vs {b}")
    capacities = doc["nominal_capacity_gib"]
    cfg = doc["config"]

    out = [
        GENERATED_WARNING.replace("length-ladder.json", "colab-memory.json"),
        "",
        f"# {doc['title']}",
        "",
        doc["summary"].strip(),
        "",
        "## Where it was measured",
        "",
    ]
    for label, header, _ in sessions:
        out.append(
            f"- **{label}:** {header['gpu']}, {header['total']} GiB, "
            f"{header['free']} GiB free to the process"
        )
    out += [
        "",
        (
            f"Probe: `{cfg['probe']}`. Batch {cfg['batch_size']}, {cfg['optimizer']}; "
            f"worst case, {cfg['worst_case']}. Measured by {cfg['measured_by']}."
        ),
        "",
        "## Peak memory, and where it fits",
        "",
        (
            "Peak memory was identical in every session. The fit columns compare it with "
            "each GPU's **nominal** capacity; only the A100's was measured."
        ),
        "",
    ]
    fit_names = list(capacities)
    time_names = [f"ms/batch, {label}" for label, _, _ in sessions]
    out.append(
        "| model | vocab | length | peak GiB | "
        + " | ".join(f"fits {n}" for n in fit_names)
        + " | "
        + " | ".join(time_names)
        + " |"
    )
    out.append("|" + "---|" * (4 + len(fit_names) + len(time_names)))
    for i, row in enumerate(first_rows):
        peak = row["peak"]
        fits = [
            "no" if peak is None or peak > capacities[n] else "yes" for n in fit_names
        ]
        times = [
            str(rows[i]["ms"]) if rows[i]["ms"] is not None else "OOM"
            for _, _, rows in sessions
        ]
        out.append(
            f"| {row['model']} | {row['vocab']:,} | {row['length']} | "
            f"{'OOM' if peak is None else f'{peak:.2f}'} | "
            + " | ".join(fits)
            + " | "
            + " | ".join(times)
            + " |"
        )

    out += ["", "What the lengths and vocabularies stand for:", ""]
    for length, meaning in cfg["lengths"].items():
        out.append(f"- **length {length}:** {meaning}")
    for vocab, meaning in cfg["vocabularies"].items():
        out.append(f"- **vocab {int(vocab):,}:** {meaning}")

    largest = max(
        (r for r in first_rows if r["peak"] is not None), key=lambda r: r["peak"]
    )
    out += [
        "",
        "## What it settles",
        "",
        (
            f"- **The largest peak is {largest['peak']:.2f} GiB** ({largest['model']}, vocab "
            f"{largest['vocab']:,}, length {largest['length']}), "
            f"{largest['peak'] / first_header['free']:.0%} of the {first_header['free']} GiB "
            f"free on the {first_header['gpu']} the first session drew."
        ),
    ]
    for name, capacity in capacities.items():
        over = [
            f"{r['model']} at vocab {r['vocab']:,}, length {r['length']}"
            for r in first_rows
            if r["peak"] is None or r["peak"] > capacity
        ]
        verdict = (
            "every configuration fits"
            if not over
            else "does not fit: " + "; ".join(over)
        )
        out.append(f"- **{name}** ({capacity} GiB nominal): {verdict}.")

    out += ["", "## Caveats", ""]
    for caveat in doc["caveats"]:
        out.append(f"- {caveat.strip()}")
    out.append("")
    return "\n".join(out)


RENDERERS = {
    "length-ladder": render_length_ladder,
    "a8-benchmark": render_a8_benchmark,
    "colab-memory": render_colab_memory,
}


def main() -> int:
    """Render every report, or check that the rendered copies are current."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if any report differs from its JSON",
    )
    args = parser.parse_args()

    stale: list[str] = []
    for name, renderer in RENDERERS.items():
        source = DATA / f"{name}.json"
        if not source.exists():
            print(f"missing {source}", file=sys.stderr)
            return 2
        expected = renderer(json.loads(source.read_text(encoding="utf-8")))
        target = REPORTS / f"{name}.md"
        current = target.read_text(encoding="utf-8") if target.exists() else None

        if args.check:
            if current != expected:
                stale.append(str(target))
            continue

        if current == expected:
            print(f"  unchanged  {target}")
        else:
            target.write_text(expected, encoding="utf-8")
            print(f"  written    {target}")

    if stale:
        print(
            "These reports are out of date with their JSON:\n"
            + "\n".join(f"  {s}" for s in stale)
            + "\n\nRun: python scripts/render_report.py",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print("  all reports current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
